version: "3"
services:
  db-service:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.db
    container_name: db-container
    image: db-image:latest
    ports:
      - "3307:3306"
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend-service:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.backend
    container_name: backend-container
    image: backend-image:latest
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - db-service
    restart: always

  frontend-service:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.frontend
    container_name: frontend-container
    image: frontend-image:latest
    ports:
      - "4200:4200"
    networks:
      - my_network
    restart: always

volumes:
  db_data:

networks:
  my_network:
