FROM node:14

WORKDIR /app

RUN npm install -g @angular/cli@14.0.7

COPY frontend/package*.json ./

RUN npm install

COPY frontend/. .

EXPOSE 4200

CMD ["ng", "serve", "--port", "4200", "--host", "0.0.0.0"]
